import type {Metadata} from 'next';
import {IBM_Plex_Sans_KR} from 'next/font/google';
import './globals.css';
import {Header} from '@/widgets/layout/header';
import {ReactNode} from 'react';
import {Footer} from '@/widgets/layout';
import {cn} from "@/shared";

const mainFont = IBM_Plex_Sans_KR({
  weight: ['300','400','500','600','700'],
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-main',
});


export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
                                     children,
                                   }: Readonly<{
  children: ReactNode;
}>) {
  return (
    <html lang="ko" className={cn(mainFont.variable, 'antialiased')}>
    <body className='font-[var(--font-main)]'>
    {children}
    </body>
    </html>
  );
}
